### ISSUE TITLE
Integration fastdotcom not updated - Fast.com can measure uploads but integration and documentation support only Downloads

### ISSUE THREAD

**Issue by user897943** [home-assistant/home-assistant.io#12106]
## The problem

Fast.com now does uploads as well as downloads, but the documentation incorrectly states that Fast.com only support measuring download speeds, both the component and the documentation must be updated to reflect the true reality.

## Environment

0.105.4
- Home Assistant release with the issue: 0.105.4
- Last working Home Assistant release (if known): Not related to version - integration not updated
- Operating environment (Hass.io/Docker/Windows/etc.): Docker
- Integration causing this issue: Fast.com
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/fastdotcom/

## Problem-relevant `configuration.yaml`

fastdotcom:
  scan_interval:
      minutes: 30
```yaml

```

## Traceback/Error logs

```txt

```

**Comment by balloob** [comment]
Updating the integration is a feature request. We use issues only for bugs. The bug is that the docs are incorrectly stating that uploads are not supported by fast.com

**Comment by frenck** [comment]
Updated the wording on the integration page to ensure it is more clear where the limitation originates from.

**Comment by user897943** [comment]
Guys, have you tried fast.com? It *does* support uploads... Once the download test is finished you get stats below it, if you click on Show More Info to see the stats you can see an upload test starts running and then you get the results a few seconds later. So I do consider this a bug because the integration isn't working fully... unless you meant to create a half-done integration in which case I guess you'd consider it a feature request, but the speedtest.net integration does both down and up so why won't this one also?

**Comment by frenck** [comment]
@user897943 The integration does NOT support it.
Adding features to integration is a feature request, not a bug.

If you want to suggest a feature, you should try our [Community Forum: Feature Requests](https://community.home-assistant.io/c/feature-requests).

If you have additional questions, feel free to join our [Discord chat server](https://discord.gg/c5DvZ4e).

Thanks! 👍
