### ISSUE TITLE
suggested reboot automation doesn't work

### ISSUE THREAD

**Issue by ollibert** [home-assistant/home-assistant.io#20653]
### Feedback

It is possible that the automation "KLF reboot on hate stop event" does not work, as is the case for me.
I suspect that hass simply shuts down too fast and thus the automation is not executed at all.

### URL

https://www.home-assistant.io/integrations/velux/

### Version

2021.11.5

**Comment by jcoetsie** [comment]
Same here, I need to recycle power on the hub to get Velux integration working again
