### ISSUE TITLE
Credit generation tool missing contributors

### ISSUE THREAD

**Issue by goyney** [home-assistant/home-assistant.io#4703]
The tool that generates the [credits page](https://home-assistant.io/developers/credits/) doesn't seem to be including all contributors properly. For example, [I contributed](https://github.com/home-assistant/home-assistant/pull/11271) for the first time in the [0.61.0 release](https://home-assistant.io/blog/2018/01/14/release-61/), but still have not been included in the list after several regenerations of the page.

I am unsure if others are missing as well.

**Comment by mririgoyen** [comment]
Any word on this issue? It's been almost two months since I reported it and I still do not show up on the Credits page. :(

**Comment by flavio20002** [comment]
Me too...I bet it's something about profile settings in github...

**Comment by fabaff** [comment]
The script is iterating over the repos and grabbing the content. Not sure, about the profile settings. I can find something that looks like "Keep my details private".

**Comment by mririgoyen** [comment]
I looked through my GitHub settings and don't see anything that would prevent my details from not being publicly available.

**Comment by mririgoyen** [comment]
This is not stale. I still do not appear.

**Comment by frenck** [comment]
I'll give this a shot.

**Comment by fabaff** [comment]
Both of you are still missing. I can't figure out why.

I think that we should integrate the credit script into `hass-release` as we have already most parts do the work in place there.

**Comment by frenck** [comment]
I've been playing on and off with it the past weeks and trying to "improve" it / getting it to work. Nevertheless, the hass-release might indeed be a better place for it.

**Comment by kariudo** [comment]
I have noticed I am also missing despite several regenerations since merged PRs. Couldn't spot any obvious reason as to why.

**Comment by WofWca** [comment]
Alright, [*this*](https://developer.github.com/v3/repos/#list-contributors) explains it, I guess:
> **only the first 500** author email addresses in the repository link to GitHub users. The rest will appear as anonymous contributors without associated GitHub user information.

Gotta find another way to obtain this data.

**Comment by goyney** [comment]
Once again.... Not stale. This is pretty crazy that's almost been a year and contributors are still not properly credited. I have not any more work on this project specifically because of this issue.

**Comment by nwesterhausen** [comment]
It seems to have all contributors listed. I see you on there as well.
![image](https://user-images.githubusercontent.com/2317381/49471282-786ada80-f7da-11e8-9929-816cc41a02f9.png)

I think this issue can be closed.

**Comment by fabaff** [comment]
Yes, the new script should catch all now.
