### ISSUE TITLE
Clarify PC instructions

### ISSUE THREAD

**Issue by xbmcnut** [home-assistant/home-assistant.io#475]
Sorry, NOOB question as I'm a hardware guy. Under the PC section, I've installed Python using [these](http://www.anthonydebarros.com/2015/08/16/setting-up-python-in-windows-10/) instructions and when I run `pip3 install fabric3` that seems to be installed but then where do I run the git command from as I'm not sure what 'Clone the repository' means? I'm assuming I'm going to end up with a directory off C: called _fabric-home-assistant_ but I'm not sure how to get to that step.

N.B My Python 3.5 instance is installed under C:\Python35-64.

**Comment by fabaff** [comment]
@jbags81 can you please have a look at this?

**Comment by jbags81** [comment]
From the [getting started section](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/):
Installation instructions (**all from your PC**):   _<---- This is done from a directory of your choosing. Like C:\scripts or C:\make_up_a_folder_here._ 

Install fabric: ```pip3 install fabric3```   _<---- You did this part already_
Clone the repository: ```git clone https://github.com/jbags81/fabric-home-assistant.git``` _<--- This is done from inside the folder or directory you used above_
Change the directory: cd fabric-home-assistant _<---- this is what's created after running the git clone command._
Edit the ```fabfile.py``` file and add the hostname or the IP address of your Raspberry Pi to env.hosts. If you are using Debian 8 then replace the username pi in the fabfile.py file with your Debian user as well.
Build your new Home Assistant server: ```fab deploy``` _<--- then run this command (you may need to specify python3 PATH if it's not set in your sys var's._
Reboot your Raspberry Pi.

**Comment by xbmcnut** [comment]
Thank you for your reply. Sorry, but still stuck. How do I know fabric is installed. When I run the command `pip3 install fabric3` from inside C:\make_up_a_folder_here I get the following.

`Command "c:\python35-64\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\peters\\AppData\\Local\\Temp\\pip-build-2jzbncze\\pycrypto\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\peters\AppData\Local\Temp\pip-919lncfz-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\peters\AppData\Local\Temp\pip-build-2jzbncze\pycrypto`

Secondly, how do I run the git command inside windows? Sorry, but unsure how to 'clone the desktop' in my Windows environment.

**Comment by xbmcnut** [comment]
OK. I need GIT for Windows! Got that and cloned the directory into C:\HA. Modified fabfile.py with Pi's IP address and removed # from IP line. I have Python variables added and can run Python from any directory but when I run `fab deploy` I get _'fab' is not recognized as an internal or external command,
operable program or batch file_ so I'm assuming fabric did not install correctly.

**Comment by Landrash** [comment]
@xbmcnut I thunk you would have a  easier time doing this manually.
The end result, is it going to be running on your windows machine or on a rPi, virtaul machine etc?

**Comment by xbmcnut** [comment]
Hi. I'm trying to follow the instructions so I can deploy on my RP2. I have it running on the Pi already (locally) but want to change to Jessie Lite under the VirtualENV environment for my go live machine and so that I can supply expanded instructions for Windows users like me that have never done this before.

**Comment by jbags81** [comment]
Closing as this is outside the scope of a AiO installer issue.
