### ISSUE TITLE
raspberry pi arduino home assistant

### ISSUE THREAD

**Issue by mizousenju** [home-assistant/home-assistant.io#506]
hi everyone,
so I am trying to connect my raspberry pi in which I installed homeassistant with arduino uno using esp 8266.
the basics are that the raspberry pi will act as a server to send and recieve data from all the arduino 
in this case , the arduino is connected with the sensors (light, humidity, temperature)
the problem I am facing is that i can't make a configuration file that seems to be able to handle all of this
any suggestions or solutions please ?

**Comment by Landrash** [comment]
This is a repository a for the Home Assistant documentation and issue track for eventual incorrect information.

For help I would suggest visiting the [gitter chatroom](https://gitter.im/home-assistant/home-assistant) or the [forum](https://community.home-assistant.io/).

**Comment by mizousenju** [comment]
ok , thanks man
