### ISSUE TITLE
Problem with Open Zwave Control Panel config on the all-in-one install

### ISSUE THREAD

**Issue by rogersmj** [home-assistant/home-assistant.io#514]
I've had a hell of a time getting Home Assistant installed with Zwave, so I tried to use the [All-In-One installer](https://home-assistant.io/getting-started/installation-raspberry-pi-all-in-one/). I ran into an issue that I was able to fix for myself, but wanted to raise it here so it could hopefully be addressed for everyone. 

This is on a fresh Jessie Lite Raspberry Pi.

The install seemed to go without a hitch, and I could load up the HA web interface. However, when I tried to start the Open Zwave control panel (as per the instructions), it complained about a missing config file:

`pi@HAL:/srv/hass/src/open-zwave-control-panel $ sudo ./ozwcp -p 8888
2016-05-27 08:27:23.265 Error, Cannot find a path to the configuration files at ./config/. Exiting...
2016-05-27 08:27:23.275 Error, Exception: Options.cpp:91 - 1 - Cannot Find Configuration Files
Error: Options.cpp:91 - Cannot Find Configuration Files`

I noticed that "config" was a simlink pointing to a path that didn't exist:

`config -> /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config`

A little exploring revealed that what did exist was:

`/srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv**6**l.egg/config`

Changed the symlink, everything worked fine. Not sure why it was originally the first link, but wanted to share in case it's a bug.

**Comment by balloob** [comment]
Ooh that's different per raspberry Pi version as they use different
architectures. Cc @jbags81

**Comment by rbray89** [comment]
I made mine point to the config in the openzwave src folder. Then I made the python install point it's configs to the same. I plan on doing the same to the zwcfg files.

**Comment by balloob** [comment]
Closing this as this is the wrong repo. I added an issue to the all in one installer repo.

**Comment by rbaindourov** [comment]
Sorry.
This was the only thing I could find on the net that seemed remotely close to what I am experiencing.

I have compiled open-zwave, libmicrohttpd, and open-zwave-control-panel on my PI3 running Raspbian.

I had some issues:
https://github.com/OpenZWave/open-zwave-control-panel/issues/42

But ultimately ended up getting stuck on this error message here:

```
pi@raspberrypi:~/zwave-cp $ ./ozwcp 
2016-06-07 20:46:51.357 Error, Cannot find a path to the configuration files at ./config/. Exiting...
2016-06-07 20:46:51.358 Error, Exception: Options.cpp:91 - 1 - Cannot Find Configuration Files
Error: Options.cpp:91 - Cannot Find Configuration Files
```

Unfortunately I don't have a `/srv/hass` folder nor do I have a `config` symlink.

Can one of you give me a push forward, so I can get the OZWCP up and running?



Thanks in Advance!

**Comment by Landrash** [comment]
@rbaindourov In our case it's a problem with an install script a lot of HomeAssistant users are using.
In your case you are missing the configuration files from Open-zwave. You should be able to make a symlink to the directory where you have the open-zwave files from when you compiled ozcp.
We have that in a subdirectory of our installation of HomeAssistant.

**Comment by rbaindourov** [comment]
Thank you! Doing `ln -s config ../open-zwave/config` solved the problem!

**Comment by boredJ** [comment]
Hello I am having the same issue. What I cannot understand is when you said:

> Changed the symlink, everything worked fine. Not sure why it was originally the first link, but wanted to share in case it's a bug.

When I looked into the config folder `/srv/homeassistant/homeassistant_venv/lib/python3.4/site-packages/libopenzwave-0.3.2-py3.4-linux-armv7l.egg/config` I could see different folders with xml files for various devices.
