### ISSUE TITLE
Just updated

### ISSUE THREAD

**Issue by DraZtiK** [home-assistant/home-assistant.io#543]
Don't really care for the additional banner as it serves no purpose. Yes, it auto hides after you scroll but takes up valuable real estate on a phone.

Can we remove it?

**Comment by balloob** [comment]
Banner?

**Comment by DraZtiK** [comment]
Sorry, Above the tabs there is now a banner/element "Home Assistant" that was not there in a previous release.

**Comment by DraZtiK** [comment]
![capture5](https://cloud.githubusercontent.com/assets/2875702/15904304/7f7fc778-2d7e-11e6-9a09-5de4e7194644.PNG)

**Comment by fabaff** [comment]
This is the issue tracker for the documentation. Frontend related issues should go [here](https://github.com/home-assistant/home-assistant-polymer/issues).
