### ISSUE TITLE
Pandora Media Player

### ISSUE THREAD

**Issue by Dracoy** [home-assistant/home-assistant.io#571]
Everything installed nicely per the instructions but I'm not able to get it to display the different options in HA.

    - media_player.pandora

I added that in group, is there something else I need to add to show the options in the example?

https://home-assistant.io/images/screenshots/pandora_player.png

Thanks!

**Comment by fabaff** [comment]
I suggest that you use the [forum](https://community.home-assistant.io) for support requests. This repository is for the Home Assistant documentation.
