### ISSUE TITLE
Installation in Virtualenv Instruction Update

### ISSUE THREAD

**Issue by bzillins** [home-assistant/home-assistant.io#624]
When following the "Installation in Virtualenv" instructions in step 1 the hass user is not added to the sudo group under ubuntu 16.04. When I attempt to launch home assistant for the first time in step 6 it failed and reminded me of xkcd 838.

**Comment by Landrash** [comment]
There should be no reason for the `hass` user to have access to `sudo`.
At what step are you requiring elevated privileges when using the `hass` user in your use-case?

I would be happy to add that to the instructions if it can be motivated but I've set up HA about 10+ times on fresh installs of debian *(jessie)*, ubuntu *(various)* and a few more. The only use-case I can imagine you would require the `hass` user to have access to `sudo` would be if your having that user running script or using a component that would require elevated privileges. Both of these use-cases should be considered edge cases and should probably no be in generalized instructions.

**Comment by bzillins** [comment]
When following the instructions for the virtualenv install you switch to
the hass user in step 3 and then run a sudo command in the "Finally... "
section of step 6.

The instructions also say "we need to be the user hass user or specify the
configuration with -c" and then execute the command without -c which I
interpreted as needing to be the hass user.

I assumed that the initial launch had to be run with superuser permissions
so I added the user to the group instead of removing sudo from the command.

It may also be helpful to explicitly state the venv should be deactivated
and include the command to deactivate it as the (hass) is missing from "$
sudo -u hass -H /srv/hass/bin/hass"

**Comment by Landrash** [comment]
From the page [Installation in Virtualenv](https://home-assistant.io/getting-started/installation-virtualenv/)
> Step 3: Become the new user
>
>This is obviously only necessary if you created a hass user, but if you did, be sure to switch to that user whenever you install things in your virtualenv, otherwise you’ll end up with mucked up permissions.

>$ sudo su -s /bin/bash hass
>The su command means ‘switch’ user. We use the ‘-s’ flag because the hass user is a system user> and doesn’t have a default shell by default (to prevent attackers from being able to log in as that user).

This `sudo` command is not run as the ``hass` user. It should be run as the normal user on your linux system. `sudo` in this case is used to elevate privileges to allow you to change to that user.

>Step 6: Install Home Assistant
>
>Once your virtualenv has been activated, you don’t need to sudo any of your pip commands. pip will be installing things in the virtualenv, which the hass user has permission to modify.
>
>(hass)$ pip3 install --upgrade homeassistant
>And that’s it… you now have Home Assistant installed, and you can be sure that every bit of it is contained in /srv/hass.

No part here requires `sudo`?

>Finally… Run Home Assistant
>
>There are two ways to launch Home Assistant. If you are in the virtualenv, you can just run hass and it will work as normal. If the virtualenv is not activated, you just use the hass executable in the bin directory mentioned earlier. There is one caveat… Because Home Assistant stores it’s configuration in the user’s home directory, we need to be the user hass user or specify the configuration with -c.
>
>$ sudo -u hass -H /srv/hass/bin/hass
>The -H flag is important. It sets the $HOME environment variable to /home/hass so hass can find its configuration.

I find no part of this unclear but it also assumes some basic Linux knowledge.

>It may also be helpful to explicitly state the venv should be deactivated
and include the command to deactivate it as the (hass) is missing from "$
sudo -u hass -H /srv/hass/bin/hass"

In this case I think less is more. It's already pretty specific. If you feel like it could be described better please [change it and submit a pull request](https://github.com/home-assistant/home-assistant.io/tree/master/source/getting-started/installation-virtualenv.markdown)

**Comment by bzillins** [comment]
> we need to be the user hass user or specify the configuration with -c.

I misunderstood this to mean that I should execute the launch command as the hass user. I should have recognized that was incorrect because the -u flag would not be required if that was the intent. 

Sorry for the confusion
