### ISSUE TITLE
Update Cloudflare configuration to allow Tor exits?

### ISSUE THREAD

**Issue by n8fr8** [home-assistant/home-assistant.io#658]
With the increased promotion of HA we are doing to the Tor community, there have been people noticing that the use of Cloudflare on the website front-end causes issues with captchas.

To stop this from happening, you need to whitelist the Tor "country code" which is T1. Instructions are provided here:
https://support.cloudflare.com/hc/en-us/articles/203306930-Does-CloudFlare-block-Tor-

Thanks!

**Comment by balloob** [comment]
Done!
