### ISSUE TITLE
Can I use your project for commercial?

### ISSUE THREAD

**Issue by reejinbouk** [home-assistant/home-assistant.io#685]
Hi, please confirm, can I use your project for commercial ? (install on own system as UI, and then sell)

**Comment by fabaff** [comment]
Home Assistant is licensed under the [MIT license](https://github.com/home-assistant/home-assistant/blob/dev/LICENSE). The only requirement is that you must include the MIT license and the  copyright notice with any copies of the software. MIT is a free license that allows one to use the software for any purpose this includes commercial use.
