### ISSUE TITLE
No rule to make target

### ISSUE THREAD

**Issue by mwoods329** [home-assistant/home-assistant.io#706]
Installation terminated with this:

[localhost] put: Makefile -> /srv/hass/src/open-zwave-control-panel/Makefile
[localhost] sudo: make
[localhost] out: make: *** No rule to make target '/srv/hass/src/python-openzwave/openzwave/cpp/src/Options.h', needed by 'ozwcp.o'.  Stop.
[localhost] out: 

Warning: sudo() received nonzero return code 2 while executing 'make'!

Subsequent attempts had the same failure.
RPi 2
Latest installation of Jessie (fresh install this AM)

**Comment by fabaff** [comment]
This is the repository for the Home Assistant documentation. You have an issue with the [AIO](https://github.com/home-assistant/fabric-home-assistant). Please open an [issue](https://github.com/home-assistant/fabric-home-assistant/issues/new) there or use the [forum](https://community.home-assistant.io/). Thanks.
