### ISSUE TITLE
Telegram notify explanation could be more clear

### ISSUE THREAD

**Issue by ThinkPadNL** [home-assistant/home-assistant.io#719]
I have migrated from a Zipato Zipabox to Home Assistant a few days ago.
The website was very helpful, but some pages could use some optimization.

For example the page of using Telegram for notifications: https://home-assistant.io/components/notify.telegram/

From the configuration part it jumps straight to the photo and location examples. But what about sending a plain old simple message? It isn't mentioned anywhere on that page. Before the 'Photo' heading, i would advise to create another paragraph that handles sending a simple text message. Like this:
----------Example--------------
**Sending a message**
    action:
      service: notify.NOTIFIER_NAME
      data:
        title: Home Assistant
        message: This is a test message sent from HASS!

- **title** (*Required*): Title of the message.
- **message** (*Required*): Put the message content here.

----------End of example--------------
This seems really stupid, but as a beginner i had to search for a while on how to send a simple message.

P.S. I hope it's OK that i make this issue. I also tried to edit the page, but it said things about forking and such, i don't have any experience with that. Please correct me if i'm wrong.

**Comment by balloob** [comment]
Did you see the edit in github.com link on the top right of the page? ☺️

**Comment by ThinkPadNL** [comment]
Yes, but i was not sure if that was the correct way to suggest something like this.
I now understand, a pull request is more like a proposal and then the developers will decide if the modification will get through or not.

I will edit the page!

**Comment by balloob** [comment]
Awesome, thanks! 

I wonder if I'll change the wording to "Propose a change on GitHub"
