### ISSUE TITLE
Translations?

### ISSUE THREAD

**Issue by MTRNord** [home-assistant/home-assistant.io#742]
Is planned to have Translations in the future or is only Englisch wanted?

**Comment by Landrash** [comment]
Feature-request and similar should be keept to the [forum](https://community.home-assistant.io/c/feature-requests) or [gitter chat](https://gitter.im/home-assistant/home-assistant).

That aside you can check whats on the roadmap at the public [tracker](https://www.pivotaltracker.com/n/projects/1250084).

**Comment by MTRNord** [comment]
ok than I close the issue :)

**Comment by fabaff** [comment]
https://community.home-assistant.io/t/localization/123
